version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    networks:
      - seq-network
    ports:
      - "5341:80"
    environment:
      - "ACCEPT_EULA=Y" 
    volumes:
      - seq-data:/data

networks:
  seq-network:
    driver: bridge

volumes:
  seq-data:
